In [55]:
# !pip install xlrd

In [56]:
import pandas as pd

mt_fire = pd.read_excel('./data/sanbul.xlsx', header=2)
mt_fire.isna().sum()

발생일시_년         0
발생일시_월         0
발생일시_일         0
발생일시_시간        0
발생일시_요일        0
진화종료시간_년       0
진화종료시간_월       0
진화종료시간_일       0
진화종료시간_시간      0
발생장소_관서        1
발생장소_시도        0
발생장소_시군구      23
발생장소_읍면      572
발생장소_동리      386
발생원인_구분      904
발생원인_세부원인      0
발생원인_기타        0
피해면적_합계        0
dtype: int64

In [57]:
mt_fire.info()

<class 'pandas.DataFrame'>
RangeIndex: 5291 entries, 0 to 5290
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   발생일시_년     5291 non-null   int64
 1   발생일시_월     5291 non-null   int64
 2   발생일시_일     5291 non-null   int64
 3   발생일시_시간    5291 non-null   str
 4   발생일시_요일    5291 non-null   str
 5   진화종료시간_년   5291 non-null   int64
 6   진화종료시간_월   5291 non-null   int64
 7   진화종료시간_일   5291 non-null   int64
 8   진화종료시간_시간  5291 non-null   str
 9   발생장소_관서    5290 non-null   str
 10  발생장소_시도    5291 non-null   str
 11  발생장소_시군구   5268 non-null   str
 12  발생장소_읍면    4719 non-null   str
 13  발생장소_동리    4905 non-null   str
 14  발생원인_구분    4387 non-null   str
 15  발생원인_세부원인  5291 non-null   str
 16  발생원인_기타    5291 non-null   str
 17  피해면적_합계    5291 non-null   float64
dtypes: float64(1), int64(6), str(11)
memory usage: 744.2 KB

In [58]:
# mt_fire['locsi'].unique()
mt_fire = mt_fire.rename(columns={'발생장소_시도':'시도'
})
mt_fire['일시'] = pd.to_datetime(mt_fire['발생일시_년'].astype(str)+'-'+mt_fire['발생일시_월'].astype(str)+'-'+mt_fire['발생일시_일'].astype(str)).dt.date

In [59]:
mt_fire.head(5)

,발생일시_년,발생일시_월,발생일시_일,발생일시_시간,발생일시_요일,진화종료시간_년,진화종료시간_월,진화종료시간_일,진화종료시간_시간,발생장소_관서,시도,발생장소_시군구,발생장소_읍면,발생장소_동리,발생원인_구분,발생원인_세부원인,발생원인_기타,피해면적_합계,일시
0,2025,12,31,15:56,수,2025,12,31,20:30,경북,경북,안동,임동,대곡,기,기타(직접입력),원인미상,0.30,2025-12-31
1,2025,12,30,11:03,화,2025,12,30,12:40,전남,전남,장흥,용산,녹원,기,기타(직접입력),태양광 전선 노출에 의한 스파크 추정,0.15,2025-12-30
2,2025,12,30,05:00,화,2025,12,30,05:47,대구,대구,동,NaN,신용,기,기타(직접입력),물탱크 모터 발화,0.02,2025-12-30
3,2025,12,29,20:00,월,2025,12,29,22:35,강원,강원,고성,거진,화포,기,기타(직접입력),원인미상,0.36,2025-12-29
4,2025,12,29,14:14,월,2025,12,29,23:51,강원,강원,강릉,연곡,신왕,입,기타(직접입력),입산자 실화추정,2.10,2025-12-29

In [60]:

mt_fire['산불발생'] = 1
mt_fire

,발생일시_년,발생일시_월,발생일시_일,발생일시_시간,발생일시_요일,진화종료시간_년,진화종료시간_월,진화종료시간_일,진화종료시간_시간,발생장소_관서,시도,발생장소_시군구,발생장소_읍면,발생장소_동리,발생원인_구분,발생원인_세부원인,발생원인_기타,피해면적_합계,일시,산불발생
0,2025,12,31,15:56,수,2025,12,31,20:30,경북,경북,안동,임동,대곡,기,기타(직접입력),원인미상,0.30,2025-12-31,1
1,2025,12,30,11:03,화,2025,12,30,12:40,전남,전남,장흥,용산,녹원,기,기타(직접입력),태양광 전선 노출에 의한 스파크 추정,0.15,2025-12-30,1
2,2025,12,30,05:00,화,2025,12,30,05:47,대구,대구,동,NaN,신용,기,기타(직접입력),물탱크 모터 발화,0.02,2025-12-30,1
3,2025,12,29,20:00,월,2025,12,29,22:35,강원,강원,고성,거진,화포,기,기타(직접입력),원인미상,0.36,2025-12-29,1
4,2025,12,29,14:14,월,2025,12,29,23:51,강원,강원,강릉,연곡,신왕,입,기타(직접입력),입산자 실화추정,2.10,2025-12-29,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5286,2016,1,8,13:20,금,2016,1,8,14:15,경북,경북,칠곡,동명,금암,쓰,기타(직접입력),쓰레기 소각,0.20,2016-01-08,1
5287,2016,1,6,17:48,수,2016,1,6,21:20,경북,경북,울진,금강송,광회,NaN,주택화재비화,주택내 불씨취급 부주의,0.30,2016-01-06,1
5288,2016,1,6,15:13,수,2016,1,6,16:30,강원,강원,고성,거진,거진,담,기타(직접입력),담뱃불 실화,0.06,2016-01-06,1
5289,2016,1,5,14:31,화,2016,1,5,17:30,경기,경기,성남 수정,NaN,금토,기,무속행위,무속행위,0.10,2016-01-05,1
5290,2016,1,3,14:03,일,2016,1,3,16:20,경북,경북,영양,청기,상청,입,기타(직접입력),입산자 실화추정,0.50,2016-01-03,1

In [61]:
weather_df = pd.read_csv('./data/weather_preprocessed.csv')
weather_df

,지점,지점명,일시,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),최대 풍속(m/s),평균 풍속(m/s),최소 상대습도(%),평균 상대습도(%),일 최심적설(cm),월,일,실효습도
0,105,강릉,2016-01-01,5.1,2.1,8.9,0.0,9.6,4.8,20.0,33.0,0.0,1.0,1.0,32.568148
1,105,강릉,2016-01-02,9.1,5.5,11.2,0.0,9.5,4.9,35.0,43.8,0.0,1.0,2.0,34.257676
2,105,강릉,2016-01-03,9.0,5.3,13.8,0.0,5.7,2.6,31.0,55.8,0.0,1.0,3.0,40.240365
3,105,강릉,2016-01-04,7.4,3.3,12.0,0.0,6.9,3.4,13.0,33.8,0.0,1.0,4.0,37.708246
4,105,강릉,2016-01-05,3.0,0.4,7.7,0.0,5.7,3.7,10.0,16.3,0.0,1.0,5.0,29.817512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348813,169,흑산도,2025-11-05,10.0,6.3,14.5,0.0,9.7,5.6,56.0,71.8,0.0,12.0,29.0,64.430387
348814,169,흑산도,2025-11-06,7.6,4.6,11.1,0.0,12.5,8.1,61.0,80.1,0.0,1.0,9.0,66.293577
348815,169,흑산도,2025-11-07,4.8,3.5,6.5,0.0,11.9,9.2,45.0,56.5,0.0,12.0,30.0,60.803697
348816,169,흑산도,2025-11-08,4.1,2.2,7.0,0.0,10.6,4.4,59.0,76.8,0.0,1.0,10.0,63.544907
348817,169,흑산도,2025-11-09,2.3,0.3,5.2,0.0,14.7,11.4,56.0,66.9,0.0,12.0,31.0,62.006687

In [62]:
weather_df.isna().sum()

지점            0
지점명           0
일시            0
평균기온(°C)      0
최저기온(°C)      0
최고기온(°C)      0
일강수량(mm)      0
최대 풍속(m/s)    0
평균 풍속(m/s)    0
최소 상대습도(%)    0
평균 상대습도(%)    0
일 최심적설(cm)    0
월             0
일             0
실효습도          0
dtype: int64

In [63]:
# weather_df['지점명'].unique()
print(mt_fire['시도'].unique())
print(weather_df['지점명'].unique())

<StringArray>
['경북', '전남', '대구', '강원', '부산', '경남', '경기', '충남', '충북', '인천', '울산', '전북', '서울',
 '광주', '대전', '세종', '제주']
Length: 17, dtype: str
<StringArray>
[     '강릉',     '강진군',      '강화',      '거제',      '거창',     '경주시',      '고산',
      '고창',     '고창군',      '고흥',     '광양시',      '광주',      '구미',      '군산',
      '금산',     '김해시',      '남원',      '남해',     '대관령',      '대구',      '대전',
     '동두천',      '동해',      '목포',      '문경',      '밀양',     '백령도',      '보령',
     '보성군',      '보은',      '봉화',      '부산',      '부안',      '부여',     '북강릉',
     '북부산',     '북창원',     '북춘천',      '산청',      '상주',     '서귀포',      '서산',
      '서울',     '서청주',      '성산',      '세종',      '속초',      '수원',     '순창군',
      '순천',      '안동',     '양산시',      '양평',      '여수',     '영광군',      '영덕',
      '영월',      '영주',      '영천',      '완도',     '울릉도',      '울산',      '울진',
      '원주',     '의령군',      '의성',      '이천',      '인제',      '인천',      '임실',
      '장수',      '장흥',      '전주',     '정선군',      '정읍',      '제주',      '제천',
 '진도(첨찰산)',     '진도군',      '진주',      '창원',      '천안',      '철원',     '청송군',
      '청주',     '추풍령',      '춘천',      '충주',      '태백',      '통영',      '파주',
      '포항',     '함양군',      '합천',      '해남',      '홍성',      '홍천',     '흑산도']
Length: 98, dtype: str

In [64]:
sido_to_locs = {

    '강원': [
        '속초','북춘천','철원','대관령','춘천','북강릉','강릉','동해',
        '원주','영월','울진','울릉도','인제','홍천','태백','정선군'
    ],

    '경기': [
        '동두천','파주','수원','양평','이천'
    ],

    '인천': [
        '백령도','인천','강화'
    ],

    '서울': [
        '서울'
    ],

    '충북': [
        '충주','청주','서청주','제천','보은'
    ],

    '충남': [
        '서산','홍성','천안','보령','부여','금산'
    ],

    '대전': [
        '대전'
    ],

    '세종': [
        '세종'
    ],

    '경북': [
        '추풍령','안동','상주','포항','봉화','영주','문경',
        '청송군','영덕','의성','구미','영천','경주시'
    ],

    '전북': [
        '군산','전주','부안','임실','정읍','남원','장수',
        '고창','고창군'
    ],

    '전남': [
        '목포','여수','흑산도','완도','순천',
        '진도(첨찰산)','보성군','강진군','장흥',
        '해남','고흥','영광군','진도군'
    ],

    '대구': [
        '대구'
    ],

    '울산': [
        '울산'
    ],

    '경남': [
        '창원','북창원','통영','진주','김해시','양산시',
        '의령군','함양군','거창','합천','밀양',
        '산청','거제','남해'
    ],

    '광주': [
        '광주'
    ],

    '부산': [
        '부산','북부산'
    ],

    '제주': [
        '제주','고산','성산','서귀포'
    ]
}

In [65]:
loc_to_sido = {}
for sido,locs in sido_to_locs.items():
    # print(locs)
    for loc in locs:
        loc_to_sido[loc] = sido
        # print(loc_to_sido)


print(type(loc_to_sido))

<class 'dict'>

In [66]:
loc_to_sido

{'속초': '강원',
 '북춘천': '강원',
 '철원': '강원',
 '대관령': '강원',
 '춘천': '강원',
 '북강릉': '강원',
 '강릉': '강원',
 '동해': '강원',
 '원주': '강원',
 '영월': '강원',
 '울진': '강원',
 '울릉도': '강원',
 '인제': '강원',
 '홍천': '강원',
 '태백': '강원',
 '정선군': '강원',
 '동두천': '경기',
 '파주': '경기',
 '수원': '경기',
 '양평': '경기',
 '이천': '경기',
 '백령도': '인천',
 '인천': '인천',
 '강화': '인천',
 '서울': '서울',
 '충주': '충북',
 '청주': '충북',
 '서청주': '충북',
 '제천': '충북',
 '보은': '충북',
 '서산': '충남',
 '홍성': '충남',
 '천안': '충남',
 '보령': '충남',
 '부여': '충남',
 '금산': '충남',
 '대전': '대전',
 '세종': '세종',
 '추풍령': '경북',
 '안동': '경북',
 '상주': '경북',
 '포항': '경북',
 '봉화': '경북',
 '영주': '경북',
 '문경': '경북',
 '청송군': '경북',
 '영덕': '경북',
 '의성': '경북',
 '구미': '경북',
 '영천': '경북',
 '경주시': '경북',
 '군산': '전북',
 '전주': '전북',
 '부안': '전북',
 '임실': '전북',
 '정읍': '전북',
 '남원': '전북',
 '장수': '전북',
 '고창': '전북',
 '고창군': '전북',
 '목포': '전남',
 '여수': '전남',
 '흑산도': '전남',
 '완도': '전남',
 '순천': '전남',
 '진도(첨찰산)': '전남',
 '보성군': '전남',
 '강진군': '전남',
 '장흥': '전남',
 '해남': '전남',
 '고흥': '전남',
 '영광군': '전남',
 '진도군': '전남',
 '대구': '대구',
 '울산': '울산',
 '창원': '경남',
 '북창원': '경남',
 '통영': '경남',
 '진주': '경남',
 '김해시': '경남',
 '양산시': '경남',
 '의령군': '경남',
 '함양군': '경남',
 '거창': '경남',
 '합천': '경남',
 '밀양': '경남',
 '산청': '경남',
 '거제': '경남',
 '남해': '경남',
 '광주': '광주',
 '부산': '부산',
 '북부산': '부산',
 '제주': '제주',
 '고산': '제주',
 '성산': '제주',
 '서귀포': '제주'}

In [67]:
weather_df['시도'] = weather_df['지점명'].map(loc_to_sido) # 속초 : 강원 --> 변환 map

# 매핑 안 된 지점은 '기타' 처리
weather_df['시도'] = weather_df['시도'].astype(str)

# 확인
print(weather_df[['지점명', '시도']].head())
weather_df

  지점명  시도
0  강릉  강원
1  강릉  강원
2  강릉  강원
3  강릉  강원
4  강릉  강원

,지점,지점명,일시,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),최대 풍속(m/s),평균 풍속(m/s),최소 상대습도(%),평균 상대습도(%),일 최심적설(cm),월,일,실효습도,시도
0,105,강릉,2016-01-01,5.1,2.1,8.9,0.0,9.6,4.8,20.0,33.0,0.0,1.0,1.0,32.568148,강원
1,105,강릉,2016-01-02,9.1,5.5,11.2,0.0,9.5,4.9,35.0,43.8,0.0,1.0,2.0,34.257676,강원
2,105,강릉,2016-01-03,9.0,5.3,13.8,0.0,5.7,2.6,31.0,55.8,0.0,1.0,3.0,40.240365,강원
3,105,강릉,2016-01-04,7.4,3.3,12.0,0.0,6.9,3.4,13.0,33.8,0.0,1.0,4.0,37.708246,강원
4,105,강릉,2016-01-05,3.0,0.4,7.7,0.0,5.7,3.7,10.0,16.3,0.0,1.0,5.0,29.817512,강원
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348813,169,흑산도,2025-11-05,10.0,6.3,14.5,0.0,9.7,5.6,56.0,71.8,0.0,12.0,29.0,64.430387,전남
348814,169,흑산도,2025-11-06,7.6,4.6,11.1,0.0,12.5,8.1,61.0,80.1,0.0,1.0,9.0,66.293577,전남
348815,169,흑산도,2025-11-07,4.8,3.5,6.5,0.0,11.9,9.2,45.0,56.5,0.0,12.0,30.0,60.803697,전남
348816,169,흑산도,2025-11-08,4.1,2.2,7.0,0.0,10.6,4.4,59.0,76.8,0.0,1.0,10.0,63.544907,전남
348817,169,흑산도,2025-11-09,2.3,0.3,5.2,0.0,14.7,11.4,56.0,66.9,0.0,12.0,31.0,62.006687,전남

In [68]:
weather_df['일시'] = pd.to_datetime(weather_df['일시']).dt.date
mt_fire['일시'] = pd.to_datetime(mt_fire['일시']).dt.date
weather_df = weather_df.dropna(subset=['시도'])

weather_sido = (
    weather_df
    .groupby(['일시', '시도'])
    .agg({
        '평균기온(°C)': 'mean',
        '최고기온(°C)': 'max',
        '일강수량(mm)': 'sum',
        '평균 상대습도(%)': 'mean',
        '최대 풍속(m/s)': 'max',
        '평균 풍속(m/s)': 'mean',
        '최저기온(°C)': 'min',
        '실효습도' : 'mean'
    })
    .reset_index()
)
weather_sido['일시'] = pd.to_datetime(weather_sido['일시'])
mt_fire['일시'] = pd.to_datetime(mt_fire['일시'])

print(weather_sido)
weather_loc_mtfire = pd.merge(weather_sido,mt_fire,how='inner',right_on=['일시','시도'], left_on=['일시','시도'])
weather_loc_mtfire

              일시  시도   평균기온(°C)  최고기온(°C)  일강수량(mm)  평균 상대습도(%)  최대 풍속(m/s)  \
0     2016-01-01  강원  11.368750      29.7      37.2   65.087500         9.6
1     2016-01-01  경기  15.160000      30.4       4.7   70.440000         5.5
2     2016-01-01  경남  18.107143      35.0      29.7   67.335714         9.9
3     2016-01-01  경북  14.615385      34.5      54.3   63.000000         9.3
4     2016-01-01  광주  27.400000      30.4       0.0   97.400000         5.2
...          ...  ..        ...       ...       ...         ...         ...
59337 2025-12-31  전남  17.276923      33.3      20.7   72.476923         9.6
59338 2025-12-31  전북  22.122222      31.0     128.4   71.522222         7.5
59339 2025-12-31  제주  18.950000      27.5      28.7   84.625000         9.0
59340 2025-12-31  충남  17.860000      30.8      44.9   77.040000         6.4
59341 2025-12-31  충북  13.950000      29.0       0.0   53.900000         5.3

       평균 풍속(m/s)  최저기온(°C)       실효습도
0        2.031250      -3.8  54.356950
1        1.760000       0.9  58.520898
2        2.135714      -4.2  57.679737
3        2.246154       0.7  54.382906
4        2.400000      25.3  83.134151
...           ...       ...        ...
59337    2.992308      -2.3  61.778907
59338    2.000000       7.9  65.196716
59339    2.350000       8.7  69.039255
59340    1.220000      -1.8  67.722265
59341    1.725000      -4.5  52.305681

[59342 rows x 10 columns]

,일시,시도,평균기온(°C),최고기온(°C),일강수량(mm),평균 상대습도(%),최대 풍속(m/s),평균 풍속(m/s),최저기온(°C),실효습도,...,진화종료시간_시간,발생장소_관서,발생장소_시군구,발생장소_읍면,발생장소_동리,발생원인_구분,발생원인_세부원인,발생원인_기타,피해면적_합계,산불발생
0,2016-01-03,경북,13.130769,30.3,47.4,64.676923,13.0,2.569231,-3.5,54.896947,...,16:20,경북,영양,청기,상청,입,기타(직접입력),입산자 실화추정,0.50,1
1,2016-01-05,경기,14.600000,30.5,8.8,70.400000,7.0,1.800000,1.7,60.803248,...,17:30,경기,성남 수정,NaN,금토,기,무속행위,무속행위,0.10,1
2,2016-01-06,강원,13.475000,33.4,12.6,56.562500,8.5,2.431250,-1.4,56.072873,...,16:30,강원,고성,거진,거진,담,기타(직접입력),담뱃불 실화,0.06,1
3,2016-01-06,경북,15.115385,32.0,26.9,71.723077,7.7,1.515385,-1.6,60.453429,...,21:20,경북,울진,금강송,광회,NaN,주택화재비화,주택내 불씨취급 부주의,0.30,1
4,2016-01-08,경북,14.538462,33.1,37.1,70.253846,9.8,2.100000,1.0,62.004730,...,14:15,경북,칠곡,동명,금암,쓰,기타(직접입력),쓰레기 소각,0.20,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5226,2025-12-29,강원,12.837500,29.0,25.5,61.006250,9.3,1.918750,-8.9,54.765202,...,22:35,강원,고성,거진,화포,기,기타(직접입력),원인미상,0.36,1
5227,2025-12-29,강원,12.837500,29.0,25.5,61.006250,9.3,1.918750,-8.9,54.765202,...,23:51,강원,강릉,연곡,신왕,입,기타(직접입력),입산자 실화추정,2.10,1
5228,2025-12-30,대구,23.900000,26.2,65.7,87.600000,5.7,2.300000,22.0,73.747447,...,05:47,대구,동,NaN,신용,기,기타(직접입력),물탱크 모터 발화,0.02,1
5229,2025-12-30,전남,16.223077,32.4,71.9,70.500000,10.1,2.500000,-3.3,61.065600,...,12:40,전남,장흥,용산,녹원,기,기타(직접입력),태양광 전선 노출에 의한 스파크 추정,0.15,1
5230,2025-12-31,경북,14.238462,34.4,43.1,60.792308,11.6,1.892308,-5.5,54.001362,...,20:30,경북,안동,임동,대곡,기,기타(직접입력),원인미상,0.30,1

In [69]:
fire_daily = (
    mt_fire
    .groupby(['시도','일시','발생장소_시군구'])
    .size()
    .reset_index(name='fire_count')
)

fire_daily['fire'] = 1
fire_daily = fire_daily[['시도','일시','fire','발생장소_시군구']]

fire_daily

      시도         일시  fire 발생장소_시군구
0     강원 2016-01-06     1       고성
1     강원 2016-01-12     1       양구
2     강원 2016-01-13     1       원주
3     강원 2016-01-19     1       강릉
4     강원 2016-01-22     1       춘천
...   ..        ...   ...      ...
5100  충북 2025-11-10     1       괴산
5101  충북 2025-11-10     1       진천
5102  충북 2025-11-24     1       단양
5103  충북 2025-12-07     1       제천
5104  충북 2025-12-08     1       충주

[5105 rows x 4 columns]

In [70]:
fire_daily['시도'].value_counts().sum()

5105

In [71]:
fire_daily

      시도         일시  fire 발생장소_시군구
0     강원 2016-01-06     1       고성
1     강원 2016-01-12     1       양구
2     강원 2016-01-13     1       원주
3     강원 2016-01-19     1       강릉
4     강원 2016-01-22     1       춘천
...   ..        ...   ...      ...
5100  충북 2025-11-10     1       괴산
5101  충북 2025-11-10     1       진천
5102  충북 2025-11-24     1       단양
5103  충북 2025-12-07     1       제천
5104  충북 2025-12-08     1       충주

[5105 rows x 4 columns]

In [72]:
# weather_sido = weather_sido.drop('지점명',axis=1)
# weather_sido

In [73]:
fire_daily = fire_daily.drop('발생장소_시군구',axis=1)

In [74]:
full_dates = pd.date_range(
    start=weather_loc_mtfire['일시'].min(),
    end=weather_loc_mtfire['일시'].max(),
    freq='D'
)

sido_list = weather_loc_mtfire['시도'].unique()
# print(sido_list)
base_df = (
    pd.MultiIndex
    .from_product([sido_list, full_dates], names=['시도','일시'])
    .to_frame(index=False)
)

print(base_df)
base_df = base_df.merge(
    fire_daily,
    on=['시도','일시'],
    how='left'
)

base_df['fire'] = base_df['fire'].fillna(0).astype(int)
base_df
base_df = base_df.merge(
    weather_sido,
    on=['시도', '일시'],
    how='left'
)

base_df

       시도         일시
0      경북 2016-01-03
1      경북 2016-01-04
2      경북 2016-01-05
3      경북 2016-01-06
4      경북 2016-01-07
...    ..        ...
62062  제주 2025-12-27
62063  제주 2025-12-28
62064  제주 2025-12-29
62065  제주 2025-12-30
62066  제주 2025-12-31

[62067 rows x 2 columns]

,시도,일시,fire,평균기온(°C),최고기온(°C),일강수량(mm),평균 상대습도(%),최대 풍속(m/s),평균 풍속(m/s),최저기온(°C),실효습도
0,경북,2016-01-03,1,13.130769,30.3,47.4,64.676923,13.0,2.569231,-3.5,54.896947
1,경북,2016-01-04,0,12.823077,32.1,327.1,69.453846,6.4,1.800000,-4.5,57.062442
2,경북,2016-01-05,0,15.569231,31.9,73.1,69.438462,11.8,1.992308,-1.2,58.688788
3,경북,2016-01-06,1,15.115385,32.0,26.9,71.723077,7.7,1.515385,-1.6,60.453429
4,경북,2016-01-07,0,14.930769,34.0,57.0,71.315385,13.2,2.400000,-1.4,61.488449
...,...,...,...,...,...,...,...,...,...,...,...
63262,제주,2025-12-27,0,14.800000,23.6,91.2,72.750000,10.7,2.400000,-0.2,64.484553
63263,제주,2025-12-28,0,15.775000,24.7,15.5,76.675000,7.8,2.938889,0.0,64.945752
63264,제주,2025-12-29,0,16.725000,24.1,47.5,77.300000,12.0,3.375000,3.7,65.626388
63265,제주,2025-12-30,0,19.225000,27.8,5.3,75.625000,14.0,4.300000,5.7,65.788278
63266,제주,2025-12-31,0,18.950000,27.5,28.7,84.625000,9.0,2.350000,8.7,69.039255

In [75]:
base_df['fire'].value_counts()

fire
0    58162
1     5105
Name: count, dtype: int64

In [81]:
base_df.to_csv('머신러닝용_ver_0.1.csv',encoding='utf-8')

In [77]:
weather_loc_mtfire

,일시,시도,평균기온(°C),최고기온(°C),일강수량(mm),평균 상대습도(%),최대 풍속(m/s),평균 풍속(m/s),최저기온(°C),실효습도,...,진화종료시간_시간,발생장소_관서,발생장소_시군구,발생장소_읍면,발생장소_동리,발생원인_구분,발생원인_세부원인,발생원인_기타,피해면적_합계,산불발생
0,2016-01-03,경북,13.130769,30.3,47.4,64.676923,13.0,2.569231,-3.5,54.896947,...,16:20,경북,영양,청기,상청,입,기타(직접입력),입산자 실화추정,0.50,1
1,2016-01-05,경기,14.600000,30.5,8.8,70.400000,7.0,1.800000,1.7,60.803248,...,17:30,경기,성남 수정,NaN,금토,기,무속행위,무속행위,0.10,1
2,2016-01-06,강원,13.475000,33.4,12.6,56.562500,8.5,2.431250,-1.4,56.072873,...,16:30,강원,고성,거진,거진,담,기타(직접입력),담뱃불 실화,0.06,1
3,2016-01-06,경북,15.115385,32.0,26.9,71.723077,7.7,1.515385,-1.6,60.453429,...,21:20,경북,울진,금강송,광회,NaN,주택화재비화,주택내 불씨취급 부주의,0.30,1
4,2016-01-08,경북,14.538462,33.1,37.1,70.253846,9.8,2.100000,1.0,62.004730,...,14:15,경북,칠곡,동명,금암,쓰,기타(직접입력),쓰레기 소각,0.20,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5226,2025-12-29,강원,12.837500,29.0,25.5,61.006250,9.3,1.918750,-8.9,54.765202,...,22:35,강원,고성,거진,화포,기,기타(직접입력),원인미상,0.36,1
5227,2025-12-29,강원,12.837500,29.0,25.5,61.006250,9.3,1.918750,-8.9,54.765202,...,23:51,강원,강릉,연곡,신왕,입,기타(직접입력),입산자 실화추정,2.10,1
5228,2025-12-30,대구,23.900000,26.2,65.7,87.600000,5.7,2.300000,22.0,73.747447,...,05:47,대구,동,NaN,신용,기,기타(직접입력),물탱크 모터 발화,0.02,1
5229,2025-12-30,전남,16.223077,32.4,71.9,70.500000,10.1,2.500000,-3.3,61.065600,...,12:40,전남,장흥,용산,녹원,기,기타(직접입력),태양광 전선 노출에 의한 스파크 추정,0.15,1
5230,2025-12-31,경북,14.238462,34.4,43.1,60.792308,11.6,1.892308,-5.5,54.001362,...,20:30,경북,안동,임동,대곡,기,기타(직접입력),원인미상,0.30,1

In [78]:
full_dates = pd.date_range(
    start='2016-01-01',
    end='2025-12-31',
    freq='D'
)
sido_list = weather_loc_mtfire['시도'].unique()
full_index = pd.MultiIndex.from_product(
    [sido_list, full_dates],
    names=['시도', '일시']
)
weather_loc_mtfire['일시'] = pd.to_datetime(weather_loc_mtfire['일시'])
full_index


base_df = pd.DataFrame(index=full_index).reset_index()
base_df
base_df = pd.merge(
    weather_loc_mtfire,base_df,
    on=['시도', '일시'],
    how='right'
)
base_df['일시'] = pd.to_datetime(base_df['일시'])
base_df
base_df

,일시,시도,평균기온(°C),최고기온(°C),일강수량(mm),평균 상대습도(%),최대 풍속(m/s),평균 풍속(m/s),최저기온(°C),실효습도,...,진화종료시간_시간,발생장소_관서,발생장소_시군구,발생장소_읍면,발생장소_동리,발생원인_구분,발생원인_세부원인,발생원인_기타,피해면적_합계,산불발생
0,2016-01-01,경북,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-01-02,경북,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-01-03,경북,13.130769,30.3,47.4,64.676923,13.0,2.569231,-3.5,54.896947,...,16:20,경북,영양,청기,상청,입,기타(직접입력),입산자 실화추정,0.5,1.0
3,2016-01-04,경북,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-01-05,경북,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63461,2025-12-27,제주,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63462,2025-12-28,제주,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63463,2025-12-29,제주,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63464,2025-12-30,제주,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63465,2025-12-31,제주,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
weather_loc_mtfire.to_csv('산불 날짜 별 날씨데이터.csv',index=False,encoding='utf-8')

In [80]:
weather_loc_mtfire

,일시,시도,평균기온(°C),최고기온(°C),일강수량(mm),평균 상대습도(%),최대 풍속(m/s),평균 풍속(m/s),최저기온(°C),실효습도,...,진화종료시간_시간,발생장소_관서,발생장소_시군구,발생장소_읍면,발생장소_동리,발생원인_구분,발생원인_세부원인,발생원인_기타,피해면적_합계,산불발생
0,2016-01-03,경북,13.130769,30.3,47.4,64.676923,13.0,2.569231,-3.5,54.896947,...,16:20,경북,영양,청기,상청,입,기타(직접입력),입산자 실화추정,0.50,1
1,2016-01-05,경기,14.600000,30.5,8.8,70.400000,7.0,1.800000,1.7,60.803248,...,17:30,경기,성남 수정,NaN,금토,기,무속행위,무속행위,0.10,1
2,2016-01-06,강원,13.475000,33.4,12.6,56.562500,8.5,2.431250,-1.4,56.072873,...,16:30,강원,고성,거진,거진,담,기타(직접입력),담뱃불 실화,0.06,1
3,2016-01-06,경북,15.115385,32.0,26.9,71.723077,7.7,1.515385,-1.6,60.453429,...,21:20,경북,울진,금강송,광회,NaN,주택화재비화,주택내 불씨취급 부주의,0.30,1
4,2016-01-08,경북,14.538462,33.1,37.1,70.253846,9.8,2.100000,1.0,62.004730,...,14:15,경북,칠곡,동명,금암,쓰,기타(직접입력),쓰레기 소각,0.20,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5226,2025-12-29,강원,12.837500,29.0,25.5,61.006250,9.3,1.918750,-8.9,54.765202,...,22:35,강원,고성,거진,화포,기,기타(직접입력),원인미상,0.36,1
5227,2025-12-29,강원,12.837500,29.0,25.5,61.006250,9.3,1.918750,-8.9,54.765202,...,23:51,강원,강릉,연곡,신왕,입,기타(직접입력),입산자 실화추정,2.10,1
5228,2025-12-30,대구,23.900000,26.2,65.7,87.600000,5.7,2.300000,22.0,73.747447,...,05:47,대구,동,NaN,신용,기,기타(직접입력),물탱크 모터 발화,0.02,1
5229,2025-12-30,전남,16.223077,32.4,71.9,70.500000,10.1,2.500000,-3.3,61.065600,...,12:40,전남,장흥,용산,녹원,기,기타(직접입력),태양광 전선 노출에 의한 스파크 추정,0.15,1
5230,2025-12-31,경북,14.238462,34.4,43.1,60.792308,11.6,1.892308,-5.5,54.001362,...,20:30,경북,안동,임동,대곡,기,기타(직접입력),원인미상,0.30,1